#Created by G.Chaitanya Krishna
#ZID:Z1815642
#Date:01/26/2017
#class:CSCI 689 sec:1
#This Makefile helps to compile and link the assign1.cc and also helps to clean the object files
assign1: assign1.o
	g++ -o assign1 assign1.o -lm
assign1.o: assign1.cc
	g++ -c -Wall assign1.cc
clean:
	rm *.o assign1
